-- TradeOff schema for Supabase PostgreSQL
-- Run this in Supabase SQL Editor before first backend start.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    display_name VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    cover_pic_url TEXT,
    profile_pic_url TEXT,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    CONSTRAINT users_role_check CHECK (role IN ('USER', 'ADMIN'))
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255),
    price DOUBLE PRECISION NOT NULL,
    seller_name VARCHAR(255),
    title VARCHAR(255),
    category VARCHAR(255),
    image_url TEXT,
    seller_email VARCHAR(255),
    location VARCHAR(255),
    item_condition VARCHAR(255),
    created_at TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    receiver_email VARCHAR(255) NOT NULL,
    sender_email VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_email VARCHAR(255),
    buyer_email VARCHAR(255) NOT NULL,
    buyer_name VARCHAR(255) NOT NULL,
    completed_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    delivery_confirmed_at TIMESTAMP(6),
    item_id BIGINT NOT NULL,
    item_price DOUBLE PRECISION NOT NULL,
    item_title VARCHAR(255) NOT NULL,
    refunded_at TIMESTAMP(6),
    seller_email VARCHAR(255) NOT NULL,
    seller_name VARCHAR(255) NOT NULL,
    status VARCHAR(30) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT transactions_status_check CHECK (
        status IN ('PENDING', 'PAYMENT_HELD', 'DELIVERY_CONFIRMED', 'COMPLETED', 'REFUNDED')
    )
);

CREATE INDEX IF NOT EXISTS idx_transactions_item_status
    ON transactions (item_id, status);

CREATE INDEX IF NOT EXISTS idx_transactions_buyer_email
    ON transactions (buyer_email);

CREATE INDEX IF NOT EXISTS idx_transactions_seller_email
    ON transactions (seller_email);

CREATE INDEX IF NOT EXISTS idx_transactions_created_at
    ON transactions (created_at);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email VARCHAR(100) NOT NULL,
    token TEXT NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_email
    ON refresh_tokens (user_email);
